# Generated by Django 5.2.6 on 2026-02-07 06:56

import config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=config.models.site_image_upload_path, verbose_name='메인 Hero 이미지')),
                ('hero_title', models.CharField(blank=True, default='New Season', max_length=100, verbose_name='Hero 타이틀')),
                ('hero_subtitle', models.CharField(blank=True, default='가장 사랑받는 아이템을 만나보세요.', max_length=200, verbose_name='Hero 서브타이틀')),
            ],
            options={
                'verbose_name': '사이트 설정',
                'verbose_name_plural': '사이트 설정',
                'db_table': 'site_settings',
            },
        ),
    ]
