# Generated by Django 5.2.6 on 2026-01-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_add_exchange_refund_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('NOT_LIKE_COLOR', '색상이 마음에 안 들어요'), ('NOT_LIKE_DESIGN', '디자인이 마음에 안 들어요'), ('LONG_TIME_DELIVERY', '배송 시간이 길어요'), ('SIMPLE_CHANGE_OF_MIND', '단순히 마음 바뀜'), ('TOO_EXPENSIVE', '너무 비싸요'), ('NO_NEED_ANYMORE', '필요 없어졌어요'), ('OTHER', '기타')], max_length=50, null=True),
        ),
    ]
